#ifndef J54J6_NetworkIdent
#define J54J6_NetworkIdent

#include <WiFiClient.h>
#include <ESP8266WiFi.h>
#include <WiFiUdp.h>
#include <ArduinoJson.h>

#include "logging.h"
#include "errorHandler.h"
#include "filemanager.h"
#include "wifiManager.h"
#include "udpManager.h"
#include "externServiceHandler.h"


typedef std::function<void()> handlerFunction;

struct networkIdentResolve  {
    bool result = false;
    IPAddress fromIP;
    int fromPort = -1;
    macAdress fromMAC;
};

struct networkAnswerResolve {
    bool changed = false;
    bool request = false; //if true this is an request, false its an Answer
    String serviceName = "n.S";
    String mac = "n.S";
    IPAddress ip = IPAddress(0,0,0,0);
    int servicePort = -1;

    void resetPack()
    {
        this->changed = false;
        this->request = false;
        this->serviceName = "n.S";
        this->mac = "n.S";
        this->ip = IPAddress(0,0,0,0);
        this->servicePort = -1;
    }
};

/*
    JsonBlueprint:
    {
        "type: " : "Request",
        "serviceName" : "<<serviceName>>",
        "MAC" : "<<MAC-Address>>",
        "IP" : "<<ipAddress>> ", //ip of target to prevent delivering to wrong device if broadcast way used - else empty (normal case)
        "servicePort" : "<<Port>>"
        "id" : "<<id>>" //id is randomGenerated by millis()+RandomNumber - used to handle multiple servicerequests if needed (later implemented)
    }
*/  

class NetworkIdent : public ErrorSlave {
    private:
        bool classDisabled = false;

        const char* className = "NetworkIdent";
        const char* serviceListPath = "/config/networkIdent/services.json"; //saved as {serviceType, port}
        int networkIdentPort = 63547;
        
        const char* serviceConfigBlueprint[1][2] = {{"NetworkIdent", "63547"}}; //port of network scanner


        //last generated id for serviceSearch - can readed with getLastID() - only if you want to use it
        long lastId = 0;

        IPAddress broadcastIP = IPAddress(255,255,255,255); //only for first Time later this Address will dynamically changed per subnet
        Filemanager* FM;
        WiFiManager* wifiManager;
        udpManager udpControl = udpManager(this->wifiManager, this->networkIdentPort);

        StaticJsonDocument<425> cacheDocument; //for loop received Data


    public:
        //Constructor
        NetworkIdent(Filemanager* FM, WiFiManager* wifiManager);

        //control
        bool beginListen();
        void stopListen();

        bool checkForService(const char* serviceName); //check if the serviceList-Json File contains a key with <<serviceName>>
        bool addService(const char* serviceName, const char* port); //try to add service to JsonFile - services that be implemented on device
        bool delService(const char* ServiceName); //delete key from Json File - delete service - services that be implemented on device
 

        //send stuff
        void sendServiceList(IPAddress ip, int port); //send own internalImplemented Services (serviceList) to ip
        void sendIP(IPAddress ip, int port); //send ip of device
        void sendHostname(IPAddress ip, int port); //send hostname of device
        void sendMAC(IPAddress ip, int port);


        //search Stuff
        void searchForService(const char* serviceName, bool generateId = true, IPAddress ip = IPAddress(255,255,255,255), int port = 63547);

        //helper
        bool createConfigFile();

        /*
            Preformat and returns a formatted message to send and use with NetworkIdent

            if request = true
                you will send an request, you need to add an serviceName if not there will be "notSet" as Service
            if request = false
                yoou will send an answerMessage for a request - in this case you don't need a serviceName, it will be dropped

            if generateId = true
                there will be an id appenden out of millis() + random(int) to use multiple requests the same time by the id you can difference it e.g if you want multiple devices for the same service (implemented later)

        */
        String formatMessage(bool request = false, bool generateId = false, String serviceName = "n.S", String MAC = "n.S", String ip = "n.S", String port = "-1", String id = "n.S");
        

        //get stuff
        StaticJsonDocument<425> getLastData();
        ulong getLastGeneratedId();


        //loop
        void loop();

        /*
        Inherited ErrorHandling
       */
        void startClass();
        void stopClass();
        void pauseClass();
        void restartClass();
        void continueClass();
};

#endif